version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "chatsystemdb"
      # MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "9998:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/chatSystem"
    ports:
      - "9999:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_NAME: "chatsystemdb"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_HOST: "db"